export const PORT = Number(process.env.Port ?? 4000);
export const MONGO_URI = process.env.MONGO_URI ?? "mongodb://127.0.0.1:27017";
export const DEFAULT_ROOMS = ["general", "random"];
export const MAX_ROOM_NAME_LENGTH = 24;
export const HISTORY_LIMIT = 50;
export const MAX_TEXT_LENGTH = 500;
export const MAX_NAME_LENGTH = 20;
export const HEARTBEAT_INTERVAL_MS = 30_000; //how often we ping
export const RATE_LIMIT_CAPACITY = 10; // burst allowance
export const RATE_LIMIT_REFILL_PER_SEC = 2;
export const SHUTDOWN_TIMEOUT_MS = 10_000; // force-exit fallback
export const JWT_ACCESS_SECRET = process.env.JWT_ACCESS_SECRET!;
export const JWT_REFRESH_SECRET = process.env.JWT_REFRESH_SECRET!;
export const ACCESS_TOKEN_TTL = process.env.ACCESS_TOKEN_TTL ?? "15m";
export const REFRESH_TOKEN_TTL = process.env.REFRESH_TOKEN_TTL ?? "7d";
export const CORS_ORIGIN = process.env.CORS_ORIGIN ?? "http://localhost:5173";
export const NODE_ENV = process.env.NODE_ENV ?? "development";
