export const PORT = Number(process.env.Port ?? 4000);
export const MONGO_URI = process.env.MONGO_URI ?? "mongodb://127.0.0.1:27017";
export const DEFAULT_ROOMS = ["general", "random"];
export const MAX_ROOM_NAME_LENGTH = 24;
export const HISTORY_LIMIT = 50;
export const MAX_TEXT_LENGTH = 500;
export const MAX_NAME_LENGTH = 20;
export const HEARTBEAT_INTERVAL_MS = 30_000; //how often we ping
export const RATE_LIMIT_CAPACITY = 10; // burst allowance
export const RATE_LIMIT_REFILL_PER_SEC = 2;
export const SHUTDOWN_TIMEOUT_MS = 10_000; // force-exit fallback
